<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'backend\\Controllers\\users' => 'modules\\backend\\controllers\\users.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'rainlab\\builder\\Plugin' => 'plugins\\rainlab\\builder\\Plugin.php',
  'rainlab\\pages\\Plugin' => 'plugins\\rainlab\\pages\\Plugin.php',
  'indikator\\backend\\Plugin' => 'plugins\\indikator\\backend\\Plugin.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
  'RainLab\\Builder\\Components\\RecordList' => 'plugins\\rainlab\\builder\\components\\RecordList.php',
  'RainLab\\Builder\\Components\\RecordDetails' => 'plugins\\rainlab\\builder\\components\\RecordDetails.php',
  'RainLab\\Pages\\Components\\ChildPages' => 'plugins\\rainlab\\pages\\components\\ChildPages.php',
  'RainLab\\Pages\\Components\\StaticPage' => 'plugins\\rainlab\\pages\\components\\StaticPage.php',
  'RainLab\\Pages\\Components\\StaticMenu' => 'plugins\\rainlab\\pages\\components\\StaticMenu.php',
  'RainLab\\Pages\\Components\\StaticBreadcrumbs' => 'plugins\\rainlab\\pages\\components\\StaticBreadcrumbs.php',
  'RainLab\\Pages\\Classes\\Snippet' => 'plugins\\rainlab\\pages\\classes\\Snippet.php',
  'RainLab\\Pages\\Classes\\Router' => 'plugins\\rainlab\\pages\\classes\\Router.php',
  'RainLab\\Pages\\Classes\\Page' => 'plugins\\rainlab\\pages\\classes\\Page.php',
  'RainLab\\Pages\\Classes\\SnippetManager' => 'plugins\\rainlab\\pages\\classes\\SnippetManager.php',
  'RainLab\\Pages\\Classes\\Controller' => 'plugins\\rainlab\\pages\\classes\\Controller.php',
  'RainLab\\Pages\\Classes\\PageList' => 'plugins\\rainlab\\pages\\classes\\PageList.php',
  'backend\\Controllers\\preferences' => 'modules\\backend\\controllers\\preferences.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
);